name: Bug report - Catalyst
description: You're running into a reproducible error while developing with Catalyst.
body:
  - type: markdown
    attributes:
      value: |
        We really appreciate the help making Catalyst better. Every issue helps!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
      placeholder: ''
    validations:
      required: true
  
  # - type: input
  #   id: code
  #   attributes:
  #     label: Link to the code that reproduces this issue
  #     description: |
  #       Please link to a **public** GitHub repository that can be used to reproduce this issue, if possible. It'll help fix the bug faster.
  #       Minimal reproductions should be created from our repository and should include only changes that contribute to the issue. 
  #     placeholder: 'https://github.com/user/my-minimal-catalyst-issue-reproduction'

  # - type: textarea
  #   id: steps
  #   attributes:
  #     label: To Reproduce
  #     description: Steps to reproduce the behavior
  #     placeholder: |
  #       1. Go to '...'
  #       2. Click on '....'
  #       3. Scroll down to '....'
  #       4. See error
  #   validations:
  #     required: true
  
  # - type: textarea
  #   id: expecteds
  #   attributes:
  #     label: Current vs. Expected behavior
  #     description: |
  #       A clear and concise description of what you expected to happen.
  #     placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead.'
  #   validations:
  #     required: true
  
  # - type: textarea
  #   id: additional
  #   attributes:
  #     label: Additional context
  #     description: |
  #       Add any other context about the problem here.
  #     placeholder: ''
