blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss a topic
    url: https://github.com/makeswift/makeswift/discussions
    about: Ask questions or discuss with other Makeswift users in discussions.
  - name: Check out our developer documentation
    url: https://docs.makeswift.com/developer/
    about: We are constantly updating our developer documentation. Check it out for guides, API references, and more.
